version: '3'

services:

  portainer:
    image: portainer/portainer
    ports:
      - "9000:9000"
    command: --no-auth -H unix:///var/run/docker.sock
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  apache:
    image: httpd:2.4
    volumes:
      - ./src:/var/www/html
      - ./docker-data/httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf
    depends_on:
      - php

  nginx:
    image: nginx:1.13
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html
      - ./docker-data/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - apache

  php:
    image: dinarys/php:7.2
    #build:
      #./docker-data/php
    volumes:
      - ./src:/var/www/html
      - ./docker-data/php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    volumes:
      - ./docker-data/mysql:/var/lib/mysql
    ports:
      - 3316:3306
    environment:
      MYSQL_ROOT_PASSWORD: qwerty

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links: 
      - mysql:db
    ports:
      - 8080:80
    environment:
      MYSQL_ROOT_PASSWORD: qwerty
    depends_on:
      - mysql